var idChnl = charIDToTypeID( "Chnl" );
var idInpt = charIDToTypeID( "Inpt" );
var idOtpt = charIDToTypeID( "Otpt" );
var idGmm = charIDToTypeID( "Gmm " );
var idsetd = charIDToTypeID( "setd" );
    var desc45 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref35 = new ActionReference();
        var idAdjL = charIDToTypeID( "AdjL" );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref35.putEnumerated( idAdjL, idOrdn, idTrgt );
    desc45.putReference( idnull, ref35 );
    var idT = charIDToTypeID( "T   " );
        var desc46 = new ActionDescriptor();
        var idpresetKind = stringIDToTypeID( "presetKind" );
        var idpresetKindType = stringIDToTypeID( "presetKindType" );
        var idpresetKindCustom = stringIDToTypeID( "presetKindCustom" );
        desc46.putEnumerated( idpresetKind, idpresetKindType, idpresetKindCustom );
        var idAdjs = charIDToTypeID( "Adjs" );
            var list26 = new ActionList();
                var desc47 = new ActionDescriptor();
                    var ref36 = new ActionReference();
                    var idRd = charIDToTypeID( "Rd  " );
                    ref36.putEnumerated( idChnl, idChnl, idRd );
                desc47.putReference( idChnl, ref36 );
                    var list27 = new ActionList();
                    list27.putInteger( %d );
                    list27.putInteger( %d );
                desc47.putList( idInpt, list27 );
                desc47.putDouble( idGmm, %f );
                    var list28 = new ActionList();
                    list28.putInteger( %d );
                    list28.putInteger( %d );
                desc47.putList( idOtpt, list28 );
            var idLvlA = charIDToTypeID( "LvlA" );
            list26.putObject( idLvlA, desc47 );
                var desc48 = new ActionDescriptor();
                    var ref37 = new ActionReference();
                    var idGrn = charIDToTypeID( "Grn " );
                    ref37.putEnumerated( idChnl, idChnl, idGrn );
                desc48.putReference( idChnl, ref37 );
                    var list29 = new ActionList();
                    list29.putInteger( %d );
                    list29.putInteger( %d );
                desc48.putList( idInpt, list29 );
                desc48.putDouble( idGmm, %f );
                    var list30 = new ActionList();
                    list30.putInteger( %d );
                    list30.putInteger( %d );
                desc48.putList( idOtpt, list30 );
            var idLvlA = charIDToTypeID( "LvlA" );
            list26.putObject( idLvlA, desc48 );
                var desc49 = new ActionDescriptor();
                    var ref38 = new ActionReference();
                    var idBl = charIDToTypeID( "Bl  " );
                    ref38.putEnumerated( idChnl, idChnl, idBl );
                desc49.putReference( idChnl, ref38 );
                    var list31 = new ActionList();
                    list31.putInteger( %d );
                    list31.putInteger( %d );
                desc49.putList( idInpt, list31 );
                desc49.putDouble( idGmm, %f );
                    var list32 = new ActionList();
                    list32.putInteger( %d );
                    list32.putInteger( %d );
                desc49.putList( idOtpt, list32 );
            var idLvlA = charIDToTypeID( "LvlA" );
            list26.putObject( idLvlA, desc49 );
        desc46.putList( idAdjs, list26 );
    var idLvls = charIDToTypeID( "Lvls" );
    desc45.putObject( idT, idLvls, desc46 );
executeAction( idsetd, desc45, DialogModes.NO );
